### ISSUE TITLE
Problem with examples on jupyter lab and python 3.9 on anaconda

### ISSUE THREAD

**Issue by manueluc3** [nansencenter/DAPPER#86]
Hi I use anaconda with python 3.9 env and after install for development dapper  I execute the example basic_1.py and give me a missing attribute error 'openblas_get_config'
DAPPER-master>python examples/basic_1.py
Traceback (most recent call last):
  File "C:\Users\ManuelJoséLazo\Downloads\DAPPER-master\examples\basic_1.py", line 13, in <module>
    import dapper.da_methods as da
  File "c:\users\manueljosélazo\downloads\dapper-master\dapper\da_methods\__init__.py", line 195, in <module>
    from .ensemble import LETKF, SL_EAKF, EnKF, EnKF_N, EnKS, EnRTS
  File "c:\users\manueljosélazo\downloads\dapper-master\dapper\da_methods\ensemble.py", line 8, in <module>
    import dapper.tools.multiproc as multiproc
  File "c:\users\manueljosélazo\downloads\dapper-master\dapper\tools\multiproc.py", line 15, in <module>
    threadpoolctl.threadpool_limits(1)
  File "C:\ProgramData\Anaconda3\envs\dapper\lib\site-packages\threadpoolctl.py", line 501, in __init__
    self._original_limits = _set_threadpool_limits(
  File "C:\ProgramData\Anaconda3\envs\dapper\lib\site-packages\threadpoolctl.py", line 182, in _set_threadpool_limits
    modules = _load_modules(prefixes=prefixes, user_api=user_api)
  File "C:\ProgramData\Anaconda3\envs\dapper\lib\site-packages\threadpoolctl.py", line 271, in _load_modules
    return _find_modules_with_enum_process_module_ex(
  File "C:\ProgramData\Anaconda3\envs\dapper\lib\site-packages\threadpoolctl.py", line 444, in _find_modules_with_enum_process_module_ex
    _get_module_info_from_path(filepath, prefixes, user_api,
  File "C:\ProgramData\Anaconda3\envs\dapper\lib\site-packages\threadpoolctl.py", line 318, in _get_module_info_from_path
    modules.append(_make_module_info(filepath, info, prefix))
  File "C:\ProgramData\Anaconda3\envs\dapper\lib\site-packages\threadpoolctl.py", line 307, in _make_module_info
    version=_get_version(dynlib, internal_api))
  File "C:\ProgramData\Anaconda3\envs\dapper\lib\site-packages\threadpoolctl.py", line 229, in _get_version
    return _get_openblas_version(dynlib)
  File "C:\ProgramData\Anaconda3\envs\dapper\lib\site-packages\threadpoolctl.py", line 252, in _get_openblas_version
    get_config = getattr(openblas_dynlib, "openblas_get_config")
  File "C:\ProgramData\Anaconda3\envs\dapper\lib\ctypes\__init__.py", line 395, in __getattr__
    func = self.__getitem__(name)
  File "C:\ProgramData\Anaconda3\envs\dapper\lib\ctypes\__init__.py", line 400, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'openblas_get_config' not found 

Maybe I have to install some python module more? Im executing on jupyter lab. Im not expert on python, by the way.
Best regards,
Manuel

**Comment by patricknraanes** [comment]
Could you try commenting out [this line](https://github.com/nansencenter/DAPPER/blob/f7477571c26d358337c4af9cba9e6f081eabfdb6/dapper/tools/multiproc.py#L15) ?

**Comment by manueluc3** [comment]
Thank you very much. That comment on that line fix the issue. I paste some snapshoot
Now I can also run other examples in jupyter lab. Nice!

**Comment by patricknraanes** [comment]
Cool! I'm not sure what the root cause here is (best guess: some form of version incompatibility with your Windows), so the fix is only a workaround. It might cause some things to be a bit slower, but for most purposes it should not matter much.
